Datadir support Issue #184
lu-zero/cargo-c pull request #185
Opened 2021-04-17 13:09 UTC by naokiri

This change adds support for installing read-only architecture-independent data files.

2021-04-17 13:13 UTC, naokiri commented on README.md
> +# Defaults to "shared/data".
I am very hesitant on using this default. Is there any good well-known directory structure for this kind of file?
At first I wanted to use  `build.rs` outputs so I tried to read `OUT_DIR` ( https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts ) but it wasn't available on running `cargo cinstall`

2021-04-17 20:02 UTC, lu-zero requested changes
I'd rather have this discussion with upstream cargo if possible. If nothing happens on their side we can look into it.

2021-04-17 22:25 UTC, naokiri commented on README.md
> +# Defaults to "shared/data".
This is the origin of the data to be installed, so the destination doesn't matter. 
In this example, `src/data` is copied to $datadir/$install_dir, which is `/usr/local/share/libfoo`

2021-09-16 11:44 UTC, lu-zero commented
All the machinery to support this use case is in the master, if you have time we can add the remaining bits this month :)

2021-11-13 04:06 UTC, closed without merging